var annotated_dup =
[
    [ "B3D", "namespaceB3D.html", [
      [ "Bank", "classB3D_1_1Bank.html", null ],
      [ "Brush", "classB3D_1_1Brush.html", null ],
      [ "Buffer", "classB3D_1_1Buffer.html", null ],
      [ "Camera", "classB3D_1_1Camera.html", null ],
      [ "Channel", "classB3D_1_1Channel.html", null ],
      [ "Effect", "classB3D_1_1Effect.html", null ],
      [ "Entity", "classB3D_1_1Entity.html", null ],
      [ "Font", "classB3D_1_1Font.html", null ],
      [ "Image", "classB3D_1_1Image.html", null ],
      [ "Light", "classB3D_1_1Light.html", null ],
      [ "Listener", "classB3D_1_1Listener.html", null ],
      [ "Matrix", "classB3D_1_1Matrix.html", null ],
      [ "Mesh", "classB3D_1_1Mesh.html", null ],
      [ "Model", "classB3D_1_1Model.html", null ],
      [ "Movie", "classB3D_1_1Movie.html", null ],
      [ "Pivot", "classB3D_1_1Pivot.html", null ],
      [ "Plane", "classB3D_1_1Plane.html", null ],
      [ "Sound", "classB3D_1_1Sound.html", null ],
      [ "Sprite", "classB3D_1_1Sprite.html", null ],
      [ "Stream", "classB3D_1_1Stream.html", null ],
      [ "Surface", "classB3D_1_1Surface.html", null ],
      [ "Terrain", "classB3D_1_1Terrain.html", null ],
      [ "Texture", "classB3D_1_1Texture.html", null ],
      [ "Timer", "classB3D_1_1Timer.html", null ]
    ] ],
    [ "CB", "namespaceCB.html", [
      [ "Console", "namespaceCB_1_1Console.html", [
        [ "Msg", "classCB_1_1Console_1_1Msg.html", null ]
      ] ],
      [ "Decal", "classCB_1_1Decal.html", null ],
      [ "Door", "classCB_1_1Door.html", null ],
      [ "Event", "classCB_1_1Event.html", null ],
      [ "Forest", "classCB_1_1Forest.html", null ],
      [ "Inventory", "classCB_1_1Inventory.html", null ],
      [ "Item", "classCB_1_1Item.html", null ],
      [ "ItemTemplate", "classCB_1_1ItemTemplate.html", null ],
      [ "MaintenanceTunnel", "classCB_1_1MaintenanceTunnel.html", null ],
      [ "NPC", "classCB_1_1NPC.html", "classCB_1_1NPC" ],
      [ "ParticleEmitter", "classCB_1_1ParticleEmitter.html", null ],
      [ "ParticleTemplate", "classCB_1_1ParticleTemplate.html", null ],
      [ "Room", "classCB_1_1Room.html", null ],
      [ "RoomTemplate", "classCB_1_1RoomTemplate.html", null ],
      [ "Sound", "classCB_1_1Sound.html", null ],
      [ "Stream", "classCB_1_1Stream.html", null ],
      [ "TempDoor", "classCB_1_1TempDoor.html", null ],
      [ "TempItem", "classCB_1_1TempItem.html", null ],
      [ "TempTriggerbox", "classCB_1_1TempTriggerbox.html", null ],
      [ "TempWaypoint", "classCB_1_1TempWaypoint.html", null ],
      [ "Triggerbox", "classCB_1_1Triggerbox.html", null ],
      [ "Waypoint", "classCB_1_1Waypoint.html", null ]
    ] ],
    [ "array", "classarray.html", null ],
    [ "carray", "classcarray.html", null ],
    [ "string", "classstring.html", null ]
];