var searchData=
[
  ['b3d_0',['B3D',['../namespaceB3D.html',1,'']]],
  ['b3d_3a_3abank_1',['Bank',['../namespaceB3D_1_1Bank.html',1,'B3D']]],
  ['b3d_3a_3abrush_2',['Brush',['../namespaceB3D_1_1Brush.html',1,'B3D']]],
  ['b3d_3a_3abuffer_3',['Buffer',['../namespaceB3D_1_1Buffer.html',1,'B3D']]],
  ['b3d_3a_3acamera_4',['Camera',['../namespaceB3D_1_1Camera.html',1,'B3D']]],
  ['b3d_3a_3aeffect_5',['Effect',['../namespaceB3D_1_1Effect.html',1,'B3D']]],
  ['b3d_3a_3afont_6',['Font',['../namespaceB3D_1_1Font.html',1,'B3D']]],
  ['b3d_3a_3aimage_7',['Image',['../namespaceB3D_1_1Image.html',1,'B3D']]],
  ['b3d_3a_3alight_8',['Light',['../namespaceB3D_1_1Light.html',1,'B3D']]],
  ['b3d_3a_3alistener_9',['Listener',['../namespaceB3D_1_1Listener.html',1,'B3D']]],
  ['b3d_3a_3amesh_10',['Mesh',['../namespaceB3D_1_1Mesh.html',1,'B3D']]],
  ['b3d_3a_3amovie_11',['Movie',['../namespaceB3D_1_1Movie.html',1,'B3D']]],
  ['b3d_3a_3apivot_12',['Pivot',['../namespaceB3D_1_1Pivot.html',1,'B3D']]],
  ['b3d_3a_3aplane_13',['Plane',['../namespaceB3D_1_1Plane.html',1,'B3D']]],
  ['b3d_3a_3asprite_14',['Sprite',['../namespaceB3D_1_1Sprite.html',1,'B3D']]],
  ['b3d_3a_3astream_20string_20entityname_15',['bool Hook_LoadRoomTemplateEntity(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1RoomTemplate.html&quot; title=&quot;CB::RoomTemplate&quot;&gt;CB::RoomTemplate&lt;/a&gt;, int rMeshVersion, &lt;a class=&quot;el&quot; href=&quot;classB3D_1_1Stream.html&quot; title=&quot;B3D::Stream&quot;&gt;B3D::Stream&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; entityName)',['../md_Articles_2Hooks.html#autotoc_md29',1,'']]],
  ['b3d_3a_3aterrain_16',['Terrain',['../namespaceB3D_1_1Terrain.html',1,'B3D']]],
  ['b3d_3a_3atexture_17',['Texture',['../namespaceB3D_1_1Texture.html',1,'B3D']]],
  ['b3d_3a_3atimer_18',['Timer',['../namespaceB3D_1_1Timer.html',1,'B3D']]],
  ['bank_19',['Bank',['../classB3D_1_1Bank.html',1,'B3D']]],
  ['bloodloss_20',['Bloodloss',['../namespaceCB_1_1Player.html#a6eec4f4b57b941e3d6975ee316cc156f',1,'CB::Player']]],
  ['bool_20hook_5fcreatedoor_20cb_3a_3adoor_20float_20x_20float_20y_20float_20z_20bool_20usecollisionmesh_21',['bool Hook_CreateDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;, float x, float y, float z, bool useCollisionMesh)',['../md_Articles_2Hooks.html#autotoc_md49',1,'']]],
  ['bool_20hook_5fcreateitem_20cb_3a_3aitem_22',['bool Hook_CreateItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md31',1,'']]],
  ['bool_20hook_5fdisablenpc_20cb_3a_3anpc_23',['bool Hook_DisableNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md48',1,'']]],
  ['bool_20hook_5fdrawhud_24',['bool Hook_DrawHUD()',['../md_Articles_2Hooks.html#autotoc_md6',1,'']]],
  ['bool_20hook_5fdrawloading_20int_20percentage_20bool_20isshortloading_25',['bool Hook_DrawLoading(int percentage, bool isShortLoading)',['../md_Articles_2Hooks.html#autotoc_md15',1,'']]],
  ['bool_20hook_5fdropitem_20cb_3a_3aitem_26',['bool Hook_DropItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md35',1,'']]],
  ['bool_20hook_5fenablenpc_20cb_3a_3anpc_27',['bool Hook_EnableNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md47',1,'']]],
  ['bool_20hook_5fexecuteconsolecommand_20string_20cmd_28',['bool Hook_ExecuteConsoleCommand(&lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; cmd)',['../md_Articles_2Hooks.html#autotoc_md12',1,'']]],
  ['bool_20hook_5ffillroom_20cb_3a_3aroom_29',['bool Hook_FillRoom(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Room.html&quot; title=&quot;CB::Room&quot;&gt;CB::Room&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md27',1,'']]],
  ['bool_20hook_5finitializeevents_30',['bool Hook_InitializeEvents()',['../md_Articles_2Hooks.html#autotoc_md25',1,'']]],
  ['bool_20hook_5fisanymenuopen_31',['bool Hook_IsAnyMenuOpen()',['../md_Articles_2Hooks.html#autotoc_md7',1,'']]],
  ['bool_20hook_5fispaused_32',['bool Hook_IsPaused()',['../md_Articles_2Hooks.html#autotoc_md8',1,'']]],
  ['bool_20hook_5fkillplayer_33',['bool Hook_KillPlayer()',['../md_Articles_2Hooks.html#autotoc_md11',1,'']]],
  ['bool_20hook_5floadentities_34',['bool Hook_LoadEntities()',['../md_Articles_2Hooks.html#autotoc_md13',1,'']]],
  ['bool_20hook_5floadroomtemplateentity_20cb_3a_3aroomtemplate_20int_20rmeshversion_20b3d_3a_3astream_20string_20entityname_35',['bool Hook_LoadRoomTemplateEntity(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1RoomTemplate.html&quot; title=&quot;CB::RoomTemplate&quot;&gt;CB::RoomTemplate&lt;/a&gt;, int rMeshVersion, &lt;a class=&quot;el&quot; href=&quot;classB3D_1_1Stream.html&quot; title=&quot;B3D::Stream&quot;&gt;B3D::Stream&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; entityName)',['../md_Articles_2Hooks.html#autotoc_md29',1,'']]],
  ['bool_20hook_5fmapconnectadjacentrooms_36',['bool Hook_MapConnectAdjacentRooms()',['../md_Articles_2Hooks.html#autotoc_md24',1,'']]],
  ['bool_20hook_5fmapcreatedoors_37',['bool Hook_MapCreateDoors()',['../md_Articles_2Hooks.html#autotoc_md23',1,'']]],
  ['bool_20hook_5fmapcreatelayout_38',['bool Hook_MapCreateLayout()',['../md_Articles_2Hooks.html#autotoc_md18',1,'']]],
  ['bool_20hook_5fmapcreaterooms_20int_20loadingstart_20float_20loadingcount_39',['bool Hook_MapCreateRooms(int loadingStart, float loadingCount)',['../md_Articles_2Hooks.html#autotoc_md21',1,'']]],
  ['bool_20hook_5fmapforcerooms_40',['bool Hook_MapForceRooms()',['../md_Articles_2Hooks.html#autotoc_md19',1,'']]],
  ['bool_20hook_5fmapinitializedimensions_41',['bool Hook_MapInitializeDimensions()',['../md_Articles_2Hooks.html#autotoc_md17',1,'']]],
  ['bool_20hook_5fmappreventroomoverlaps_42',['bool Hook_MapPreventRoomOverlaps()',['../md_Articles_2Hooks.html#autotoc_md22',1,'']]],
  ['bool_20hook_5fmapsetrooms_43',['bool Hook_MapSetRooms()',['../md_Articles_2Hooks.html#autotoc_md20',1,'']]],
  ['bool_20hook_5fmouselook_44',['bool Hook_MouseLook()',['../md_Articles_2Hooks.html#autotoc_md10',1,'']]],
  ['bool_20hook_5fmoveplayer_45',['bool Hook_MovePlayer()',['../md_Articles_2Hooks.html#autotoc_md9',1,'']]],
  ['bool_20hook_5fpickitem_20cb_3a_3aitem_46',['bool Hook_PickItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md34',1,'']]],
  ['bool_20hook_5fremovenpc_20cb_3a_3anpc_47',['bool Hook_RemoveNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md40',1,'']]],
  ['bool_20hook_5fupdatedoor_20cb_3a_3adoor_48',['bool Hook_UpdateDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md51',1,'']]],
  ['bool_20hook_5fupdateevent_20cb_3a_3aevent_49',['bool Hook_UpdateEvent(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Event.html&quot; title=&quot;CB::Event&quot;&gt;CB::Event&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md26',1,'']]],
  ['bool_20hook_5fupdateitem_20cb_3a_3aitem_50',['bool Hook_UpdateItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md32',1,'']]],
  ['bool_20hook_5fupdatemusic_51',['bool Hook_UpdateMusic()',['../md_Articles_2Hooks.html#autotoc_md16',1,'']]],
  ['bool_20hook_5fupdatenpc_20cb_3a_3anpc_52',['bool Hook_UpdateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md41',1,'']]],
  ['bool_20hook_5fuse914_20cb_3a_3aitem_20cb_3a_3ascp914_3a_3asetting_20float_20x_20float_20y_20float_20z_53',['bool Hook_Use914(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;, CB::SCP914::Setting, float x, float y, float z)',['../md_Articles_2Hooks.html#autotoc_md54',1,'']]],
  ['bool_20hook_5fusedoor_20cb_3a_3adoor_20bool_20showmsg_20bool_20playsfx_54',['bool Hook_UseDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;, bool showMsg, bool playSFX)',['../md_Articles_2Hooks.html#autotoc_md53',1,'']]],
  ['bool_20isplural_55',['string Hook_ConsoleNPCTypeToName(CB::NPC::Type type, bool isPlural)',['../md_Articles_2Hooks.html#autotoc_md43',1,'']]],
  ['bool_20isshortloading_56',['bool Hook_DrawLoading(int percentage, bool isShortLoading)',['../md_Articles_2Hooks.html#autotoc_md15',1,'']]],
  ['bool_20playsfx_57',['bool playSFX',['../md_Articles_2Hooks.html#autotoc_md53',1,'bool Hook_UseDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;, bool showMsg, bool playSFX)'],['../md_Articles_2Hooks.html#autotoc_md52',1,'int Hook_CanUseDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;, bool showMsg, bool playSFX)']]],
  ['bool_20showmsg_20bool_20playsfx_58',['bool showMsg bool playSFX',['../md_Articles_2Hooks.html#autotoc_md53',1,'bool Hook_UseDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;, bool showMsg, bool playSFX)'],['../md_Articles_2Hooks.html#autotoc_md52',1,'int Hook_CanUseDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;, bool showMsg, bool playSFX)']]],
  ['bool_20usecollisionmesh_59',['bool Hook_CreateDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;, float x, float y, float z, bool useCollisionMesh)',['../md_Articles_2Hooks.html#autotoc_md49',1,'']]],
  ['brush_60',['Brush',['../classB3D_1_1Brush.html',1,'B3D']]],
  ['buffer_61',['Buffer',['../classB3D_1_1Buffer.html',1,'B3D']]]
];
