var searchData=
[
  ['hook_5fcanusedoor_20cb_3a_3adoor_20bool_20showmsg_20bool_20playsfx_0',['int Hook_CanUseDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;, bool showMsg, bool playSFX)',['../md_Articles_2Hooks.html#autotoc_md46',1,'']]],
  ['hook_5fcombineitems_20cb_3a_3aitem_20draggeditem_20cb_3a_3aitem_20draggedontoitem_1',['void Hook_CombineItems(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; draggedItem, &lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; draggedOntoItem)',['../md_Articles_2Hooks.html#autotoc_md34',1,'']]],
  ['hook_5fconsolecheckcanchangenpcspeed_20cb_3a_3anpc_3a_3atype_20type_2',['int Hook_ConsoleCheckCanChangeNPCSpeed(CB::NPC::Type type)',['../md_Articles_2Hooks.html#autotoc_md42',1,'']]],
  ['hook_5fconsolecheckcantogglenpc_20cb_3a_3anpc_3a_3atype_20type_3',['int Hook_ConsoleCheckCanToggleNPC(CB::NPC::Type type)',['../md_Articles_2Hooks.html#autotoc_md43',1,'']]],
  ['hook_5fconsolenpcnametotype_20string_20name_4',['CB::NPC::Type Hook_ConsoleNPCNameToType(&lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; name)',['../md_Articles_2Hooks.html#autotoc_md39',1,'']]],
  ['hook_5fconsolenpctypetoname_20cb_3a_3anpc_3a_3atype_20type_20bool_20isplural_5',['string Hook_ConsoleNPCTypeToName(CB::NPC::Type type, bool isPlural)',['../md_Articles_2Hooks.html#autotoc_md40',1,'']]],
  ['hook_5fconsolespawnnpc_20cb_3a_3anpc_3a_3atype_20type_6',['int Hook_ConsoleSpawnNPC(CB::NPC::Type type)',['../md_Articles_2Hooks.html#autotoc_md41',1,'']]],
  ['hook_5fcreateitem_20cb_3a_3aitem_7',['bool Hook_CreateItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md28',1,'']]],
  ['hook_5fcreatenpc_20cb_3a_3anpc_8',['void Hook_CreateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md35',1,'']]],
  ['hook_5fdisablenpc_20cb_3a_3anpc_9',['bool Hook_DisableNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md45',1,'']]],
  ['hook_5fdrawhud_10',['bool Hook_DrawHUD()',['../md_Articles_2Hooks.html#autotoc_md6',1,'']]],
  ['hook_5fdrawloading_20int_20percentage_20bool_20isshortloading_11',['bool Hook_DrawLoading(int percentage, bool isShortLoading)',['../md_Articles_2Hooks.html#autotoc_md13',1,'']]],
  ['hook_5fdropitem_20cb_3a_3aitem_12',['bool Hook_DropItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md32',1,'']]],
  ['hook_5fenablenpc_20cb_3a_3anpc_13',['bool Hook_EnableNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md44',1,'']]],
  ['hook_5fexecuteconsolecommand_20string_20cmd_14',['bool Hook_ExecuteConsoleCommand(&lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; cmd)',['../md_Articles_2Hooks.html#autotoc_md10',1,'']]],
  ['hook_5ffillroom_20cb_3a_3aroom_15',['bool Hook_FillRoom(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Room.html&quot; title=&quot;CB::Room&quot;&gt;CB::Room&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md24',1,'']]],
  ['hook_5finitialize_16',['void Hook_Initialize()',['../md_Articles_2Hooks.html#autotoc_md2',1,'']]],
  ['hook_5finitializeevents_17',['bool Hook_InitializeEvents()',['../md_Articles_2Hooks.html#autotoc_md22',1,'']]],
  ['hook_5finitializelauncher_18',['void Hook_InitializeLauncher()',['../md_Articles_2Hooks.html#autotoc_md1',1,'']]],
  ['hook_5fkillplayer_19',['bool Hook_KillPlayer()',['../md_Articles_2Hooks.html#autotoc_md9',1,'']]],
  ['hook_5floadentities_20',['bool Hook_LoadEntities()',['../md_Articles_2Hooks.html#autotoc_md11',1,'']]],
  ['hook_5floadroomtemplateentity_20cb_3a_3aroomtemplate_20int_20rmeshversion_20b3d_3a_3astream_20string_20entityname_21',['bool Hook_LoadRoomTemplateEntity(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1RoomTemplate.html&quot; title=&quot;CB::RoomTemplate&quot;&gt;CB::RoomTemplate&lt;/a&gt;, int rMeshVersion, &lt;a class=&quot;el&quot; href=&quot;classB3D_1_1Stream.html&quot; title=&quot;B3D::Stream&quot;&gt;B3D::Stream&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; entityName)',['../md_Articles_2Hooks.html#autotoc_md26',1,'']]],
  ['hook_5fmapconnectadjacentrooms_22',['bool Hook_MapConnectAdjacentRooms()',['../md_Articles_2Hooks.html#autotoc_md21',1,'']]],
  ['hook_5fmapcreatedoors_23',['bool Hook_MapCreateDoors()',['../md_Articles_2Hooks.html#autotoc_md20',1,'']]],
  ['hook_5fmapcreatelayout_24',['bool Hook_MapCreateLayout()',['../md_Articles_2Hooks.html#autotoc_md15',1,'']]],
  ['hook_5fmapcreaterooms_20int_20loadingstart_20float_20loadingcount_25',['bool Hook_MapCreateRooms(int loadingStart, float loadingCount)',['../md_Articles_2Hooks.html#autotoc_md18',1,'']]],
  ['hook_5fmapforcerooms_26',['bool Hook_MapForceRooms()',['../md_Articles_2Hooks.html#autotoc_md16',1,'']]],
  ['hook_5fmapinitializedimensions_27',['bool Hook_MapInitializeDimensions()',['../md_Articles_2Hooks.html#autotoc_md14',1,'']]],
  ['hook_5fmappreventroomoverlaps_28',['bool Hook_MapPreventRoomOverlaps()',['../md_Articles_2Hooks.html#autotoc_md19',1,'']]],
  ['hook_5fmapsetrooms_29',['bool Hook_MapSetRooms()',['../md_Articles_2Hooks.html#autotoc_md17',1,'']]],
  ['hook_5fmouselook_30',['bool Hook_MouseLook()',['../md_Articles_2Hooks.html#autotoc_md8',1,'']]],
  ['hook_5fmoveplayer_31',['bool Hook_MovePlayer()',['../md_Articles_2Hooks.html#autotoc_md7',1,'']]],
  ['hook_5fnullgame_32',['void Hook_NullGame()',['../md_Articles_2Hooks.html#autotoc_md12',1,'']]],
  ['hook_5fpickitem_20cb_3a_3aitem_33',['bool Hook_PickItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md31',1,'']]],
  ['hook_5fpostcreatenpc_20cb_3a_3anpc_34',['void Hook_PostCreateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md36',1,'']]],
  ['hook_5fpostfillroom_20cb_3a_3aroom_35',['void Hook_PostFillRoom(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Room.html&quot; title=&quot;CB::Room&quot;&gt;CB::Room&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md25',1,'']]],
  ['hook_5fpostload_36',['void Hook_PostLoad()',['../md_Articles_2Hooks.html#autotoc_md27',1,'']]],
  ['hook_5fremoveitem_20cb_3a_3aitem_37',['void Hook_RemoveItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md30',1,'']]],
  ['hook_5fremovenpc_20cb_3a_3anpc_38',['bool Hook_RemoveNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md37',1,'']]],
  ['hook_5fsaveoptions_39',['void Hook_SaveOptions()',['../md_Articles_2Hooks.html#autotoc_md4',1,'']]],
  ['hook_5fselectitem_20cb_3a_3aitem_40',['void Hook_SelectItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md33',1,'']]],
  ['hook_5fshutdown_41',['void Hook_Shutdown()',['../md_Articles_2Hooks.html#autotoc_md3',1,'']]],
  ['hook_5fupdate_42',['void Hook_Update()',['../md_Articles_2Hooks.html#autotoc_md5',1,'']]],
  ['hook_5fupdateevent_20cb_3a_3aevent_43',['bool Hook_UpdateEvent(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Event.html&quot; title=&quot;CB::Event&quot;&gt;CB::Event&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md23',1,'']]],
  ['hook_5fupdateitem_20cb_3a_3aitem_44',['bool Hook_UpdateItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md29',1,'']]],
  ['hook_5fupdatenpc_20cb_3a_3anpc_45',['bool Hook_UpdateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md38',1,'']]],
  ['hook_5fuse914_20cb_3a_3aitem_20cb_3a_3ascp914_3a_3asetting_20float_20x_20float_20y_20float_20z_46',['bool Hook_Use914(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;, CB::SCP914::Setting, float x, float y, float z)',['../md_Articles_2Hooks.html#autotoc_md48',1,'']]],
  ['hook_5fusedoor_20cb_3a_3adoor_20bool_20showmsg_20bool_20playsfx_47',['bool Hook_UseDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;, bool showMsg, bool playSFX)',['../md_Articles_2Hooks.html#autotoc_md47',1,'']]],
  ['hooks_48',['Hooks',['../md_Articles_2Hooks.html',1,'']]]
];
