var searchData=
[
  ['camera_0',['Camera',['../classB3D_1_1Camera.html',1,'B3D']]],
  ['carray_2d1_2dg_1',['carray-1-g',['../classcarray-1-g.html',1,'']]],
  ['cb_2',['CB',['../namespaceCB.html',1,'']]],
  ['cb_3a_3aachievement_3',['Achievement',['../namespaceCB_1_1Achievement.html',1,'CB']]],
  ['cb_3a_3aachievementmessage_4',['AchievementMessage',['../namespaceCB_1_1AchievementMessage.html',1,'CB']]],
  ['cb_3a_3aconsole_5',['Console',['../namespaceCB_1_1Console.html',1,'CB']]],
  ['cb_3a_3aconsole_3a_3amsg_6',['Msg',['../namespaceCB_1_1Console_1_1Msg.html',1,'CB::Console']]],
  ['cb_3a_3adecal_7',['Decal',['../namespaceCB_1_1Decal.html',1,'CB']]],
  ['cb_3a_3adifficulty_8',['Difficulty',['../namespaceCB_1_1Difficulty.html',1,'CB']]],
  ['cb_3a_3adoor_9',['CB::Door',['../md_Articles_2Hooks.html#autotoc_md51',1,'bool Hook_UpdateDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;)'],['../namespaceCB_1_1Door.html',1,'CB.Door'],['../md_Articles_2Hooks.html#autotoc_md50',1,'void Hook_PostCreateDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;)']]],
  ['cb_3a_3adoor_20bool_20showmsg_20bool_20playsfx_10',['CB::Door bool showMsg bool playSFX',['../md_Articles_2Hooks.html#autotoc_md53',1,'bool Hook_UseDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;, bool showMsg, bool playSFX)'],['../md_Articles_2Hooks.html#autotoc_md52',1,'int Hook_CanUseDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;, bool showMsg, bool playSFX)']]],
  ['cb_3a_3adoor_20float_20x_20float_20y_20float_20z_20bool_20usecollisionmesh_11',['bool Hook_CreateDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;, float x, float y, float z, bool useCollisionMesh)',['../md_Articles_2Hooks.html#autotoc_md49',1,'']]],
  ['cb_3a_3adreamfilter_12',['Dreamfilter',['../namespaceCB_1_1Dreamfilter.html',1,'CB']]],
  ['cb_3a_3aending_13',['Ending',['../namespaceCB_1_1Ending.html',1,'CB']]],
  ['cb_3a_3aevent_14',['CB::Event',['../md_Articles_2Hooks.html#autotoc_md26',1,'bool Hook_UpdateEvent(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Event.html&quot; title=&quot;CB::Event&quot;&gt;CB::Event&lt;/a&gt;)'],['../namespaceCB_1_1Event.html',1,'CB.Event']]],
  ['cb_3a_3aforest_15',['Forest',['../namespaceCB_1_1Forest.html',1,'CB']]],
  ['cb_3a_3ainput_16',['Input',['../namespaceCB_1_1Input.html',1,'CB']]],
  ['cb_3a_3ainventory_17',['Inventory',['../namespaceCB_1_1Inventory.html',1,'CB']]],
  ['cb_3a_3aitem_18',['CB::Item',['../md_Articles_2Hooks.html#autotoc_md31',1,'bool Hook_CreateItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md35',1,'bool Hook_DropItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md34',1,'bool Hook_PickItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md32',1,'bool Hook_UpdateItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../namespaceCB_1_1Item.html',1,'CB.Item'],['../md_Articles_2Hooks.html#autotoc_md33',1,'void Hook_RemoveItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md36',1,'void Hook_SelectItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)']]],
  ['cb_3a_3aitem_20cb_3a_3ascp914_3a_3asetting_20float_20x_20float_20y_20float_20z_19',['bool Hook_Use914(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;, CB::SCP914::Setting, float x, float y, float z)',['../md_Articles_2Hooks.html#autotoc_md54',1,'']]],
  ['cb_3a_3aitem_20draggeditem_20cb_3a_3aitem_20draggedontoitem_20',['void Hook_CombineItems(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; draggedItem, &lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; draggedOntoItem)',['../md_Articles_2Hooks.html#autotoc_md37',1,'']]],
  ['cb_3a_3aitem_20draggedontoitem_21',['void Hook_CombineItems(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; draggedItem, &lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; draggedOntoItem)',['../md_Articles_2Hooks.html#autotoc_md37',1,'']]],
  ['cb_3a_3aitemtemplate_22',['ItemTemplate',['../namespaceCB_1_1ItemTemplate.html',1,'CB']]],
  ['cb_3a_3amaintenancetunnel_23',['MaintenanceTunnel',['../namespaceCB_1_1MaintenanceTunnel.html',1,'CB']]],
  ['cb_3a_3amap_24',['Map',['../namespaceCB_1_1Map.html',1,'CB']]],
  ['cb_3a_3amenu_25',['Menu',['../namespaceCB_1_1Menu.html',1,'CB']]],
  ['cb_3a_3amusic_26',['Music',['../namespaceCB_1_1Music.html',1,'CB']]],
  ['cb_3a_3anpc_27',['CB::NPC',['../md_Articles_2Hooks.html#autotoc_md48',1,'bool Hook_DisableNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md47',1,'bool Hook_EnableNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md40',1,'bool Hook_RemoveNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md41',1,'bool Hook_UpdateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../namespaceCB_1_1NPC.html',1,'CB.NPC'],['../md_Articles_2Hooks.html#autotoc_md38',1,'void Hook_CreateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md39',1,'void Hook_PostCreateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)']]],
  ['cb_3a_3anpc_3a_3atype_20hook_5fconsolenpcnametotype_20string_20name_28',['CB::NPC::Type Hook_ConsoleNPCNameToType(&lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; name)',['../md_Articles_2Hooks.html#autotoc_md42',1,'']]],
  ['cb_3a_3anpc_3a_3atype_20type_29',['CB::NPC::Type type',['../md_Articles_2Hooks.html#autotoc_md45',1,'int Hook_ConsoleCheckCanChangeNPCSpeed(CB::NPC::Type type)'],['../md_Articles_2Hooks.html#autotoc_md46',1,'int Hook_ConsoleCheckCanToggleNPC(CB::NPC::Type type)'],['../md_Articles_2Hooks.html#autotoc_md44',1,'int Hook_ConsoleSpawnNPC(CB::NPC::Type type)']]],
  ['cb_3a_3anpc_3a_3atype_20type_20bool_20isplural_30',['string Hook_ConsoleNPCTypeToName(CB::NPC::Type type, bool isPlural)',['../md_Articles_2Hooks.html#autotoc_md43',1,'']]],
  ['cb_3a_3aoptions_31',['Options',['../namespaceCB_1_1Options.html',1,'CB']]],
  ['cb_3a_3aparticles_32',['Particles',['../namespaceCB_1_1Particles.html',1,'CB']]],
  ['cb_3a_3aplayer_33',['Player',['../namespaceCB_1_1Player.html',1,'CB']]],
  ['cb_3a_3aqueuedsubtitlemsg_34',['QueuedSubtitleMsg',['../namespaceCB_1_1QueuedSubtitleMsg.html',1,'CB']]],
  ['cb_3a_3aroom_35',['CB::Room',['../md_Articles_2Hooks.html#autotoc_md27',1,'bool Hook_FillRoom(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Room.html&quot; title=&quot;CB::Room&quot;&gt;CB::Room&lt;/a&gt;)'],['../namespaceCB_1_1Room.html',1,'CB.Room'],['../md_Articles_2Hooks.html#autotoc_md28',1,'void Hook_PostFillRoom(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Room.html&quot; title=&quot;CB::Room&quot;&gt;CB::Room&lt;/a&gt;)']]],
  ['cb_3a_3aroomtemplate_36',['RoomTemplate',['../namespaceCB_1_1RoomTemplate.html',1,'CB']]],
  ['cb_3a_3aroomtemplate_20int_20rmeshversion_20b3d_3a_3astream_20string_20entityname_37',['bool Hook_LoadRoomTemplateEntity(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1RoomTemplate.html&quot; title=&quot;CB::RoomTemplate&quot;&gt;CB::RoomTemplate&lt;/a&gt;, int rMeshVersion, &lt;a class=&quot;el&quot; href=&quot;classB3D_1_1Stream.html&quot; title=&quot;B3D::Stream&quot;&gt;B3D::Stream&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; entityName)',['../md_Articles_2Hooks.html#autotoc_md29',1,'']]],
  ['cb_3a_3ascp914_38',['SCP914',['../namespaceCB_1_1SCP914.html',1,'CB']]],
  ['cb_3a_3ascp914_3a_3asetting_20float_20x_20float_20y_20float_20z_39',['bool Hook_Use914(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;, CB::SCP914::Setting, float x, float y, float z)',['../md_Articles_2Hooks.html#autotoc_md54',1,'']]],
  ['cb_3a_3askybox_40',['Skybox',['../namespaceCB_1_1Skybox.html',1,'CB']]],
  ['cb_3a_3asound_41',['Sound',['../namespaceCB_1_1Sound.html',1,'CB']]],
  ['cb_3a_3asubtitlebox_42',['SubtitleBox',['../namespaceCB_1_1SubtitleBox.html',1,'CB']]],
  ['cb_3a_3asubtitlecolor_43',['SubtitleColor',['../namespaceCB_1_1SubtitleColor.html',1,'CB']]],
  ['cb_3a_3asubtitleentry_44',['SubtitleEntry',['../namespaceCB_1_1SubtitleEntry.html',1,'CB']]],
  ['cb_3a_3asubtitlemsg_45',['SubtitleMsg',['../namespaceCB_1_1SubtitleMsg.html',1,'CB']]],
  ['cb_3a_3asubtitles_46',['Subtitles',['../namespaceCB_1_1Subtitles.html',1,'CB']]],
  ['cb_3a_3asubtitletoken_47',['SubtitleToken',['../namespaceCB_1_1SubtitleToken.html',1,'CB']]],
  ['cb_3a_3atempdoor_48',['TempDoor',['../namespaceCB_1_1TempDoor.html',1,'CB']]],
  ['cb_3a_3atempitem_49',['TempItem',['../namespaceCB_1_1TempItem.html',1,'CB']]],
  ['cb_3a_3atemptriggerbox_50',['TempTriggerbox',['../namespaceCB_1_1TempTriggerbox.html',1,'CB']]],
  ['cb_3a_3atempwaypoint_51',['TempWaypoint',['../namespaceCB_1_1TempWaypoint.html',1,'CB']]],
  ['cb_3a_3atriggerbox_52',['Triggerbox',['../namespaceCB_1_1Triggerbox.html',1,'CB']]],
  ['cb_3a_3awaypoint_53',['Waypoint',['../namespaceCB_1_1Waypoint.html',1,'CB']]],
  ['channel_54',['Channel',['../classB3D_1_1Channel.html',1,'B3D']]],
  ['cmd_55',['bool Hook_ExecuteConsoleCommand(&lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; cmd)',['../md_Articles_2Hooks.html#autotoc_md12',1,'']]],
  ['create_56',['Create',['../namespaceCB_1_1Event.html#a516feb1e608fd80640c9b79d516b7bda',1,'CB::Event']]],
  ['createmessage_57',['CreateMessage',['../namespaceCB_1_1Console.html#ac85ce1c9e2b34f03d873594300e252a1',1,'CB::Console']]],
  ['cstr_58',['cstr',['../classcstr.html',1,'']]],
  ['current096_59',['Current096',['../classCB_1_1NPC.html#a15bfa4204bdb382ff5ac38ee879958a4',1,'CB::NPC']]],
  ['current106_60',['Current106',['../classCB_1_1NPC.html#a60f67757f176405122f108a7c02f4d9e',1,'CB::NPC']]],
  ['current173_61',['Current173',['../classCB_1_1NPC.html#afaa32cd320b6bcc5c1269fe4f1bcaa6d',1,'CB::NPC']]],
  ['current5131_62',['Current5131',['../classCB_1_1NPC.html#a781cd1d69dfa817bfc6535bc6747a04b',1,'CB::NPC']]],
  ['currentroom_63',['CurrentRoom',['../namespaceCB_1_1Player.html#ab6b180720c958fc513ac7fe9513a537b',1,'CB::Player']]],
  ['currentzone_64',['CurrentZone',['../namespaceCB_1_1Player.html#a0d0fe2f973ca20596b9efcb1bab8b8b6',1,'CB::Player']]]
];
