var searchData=
[
  ['cb_3a_3adoor_20bool_20showmsg_20bool_20playsfx_0',['CB::Door bool showMsg bool playSFX',['../md_Articles_2Hooks.html#autotoc_md47',1,'bool Hook_UseDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;, bool showMsg, bool playSFX)'],['../md_Articles_2Hooks.html#autotoc_md46',1,'int Hook_CanUseDoor(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Door.html&quot; title=&quot;CB::Door&quot;&gt;CB::Door&lt;/a&gt;, bool showMsg, bool playSFX)']]],
  ['cb_3a_3aevent_1',['bool Hook_UpdateEvent(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Event.html&quot; title=&quot;CB::Event&quot;&gt;CB::Event&lt;/a&gt;)',['../md_Articles_2Hooks.html#autotoc_md23',1,'']]],
  ['cb_3a_3aitem_2',['CB::Item',['../md_Articles_2Hooks.html#autotoc_md28',1,'bool Hook_CreateItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md32',1,'bool Hook_DropItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md31',1,'bool Hook_PickItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md29',1,'bool Hook_UpdateItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md30',1,'void Hook_RemoveItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md33',1,'void Hook_SelectItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)']]],
  ['cb_3a_3aitem_20cb_3a_3ascp914_3a_3asetting_20float_20x_20float_20y_20float_20z_3',['bool Hook_Use914(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;, CB::SCP914::Setting, float x, float y, float z)',['../md_Articles_2Hooks.html#autotoc_md48',1,'']]],
  ['cb_3a_3aitem_20draggeditem_20cb_3a_3aitem_20draggedontoitem_4',['void Hook_CombineItems(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; draggedItem, &lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; draggedOntoItem)',['../md_Articles_2Hooks.html#autotoc_md34',1,'']]],
  ['cb_3a_3aitem_20draggedontoitem_5',['void Hook_CombineItems(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; draggedItem, &lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; draggedOntoItem)',['../md_Articles_2Hooks.html#autotoc_md34',1,'']]],
  ['cb_3a_3anpc_6',['CB::NPC',['../md_Articles_2Hooks.html#autotoc_md45',1,'bool Hook_DisableNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md44',1,'bool Hook_EnableNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md37',1,'bool Hook_RemoveNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md38',1,'bool Hook_UpdateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md35',1,'void Hook_CreateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md36',1,'void Hook_PostCreateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)']]],
  ['cb_3a_3anpc_3a_3atype_20hook_5fconsolenpcnametotype_20string_20name_7',['CB::NPC::Type Hook_ConsoleNPCNameToType(&lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; name)',['../md_Articles_2Hooks.html#autotoc_md39',1,'']]],
  ['cb_3a_3anpc_3a_3atype_20type_8',['CB::NPC::Type type',['../md_Articles_2Hooks.html#autotoc_md42',1,'int Hook_ConsoleCheckCanChangeNPCSpeed(CB::NPC::Type type)'],['../md_Articles_2Hooks.html#autotoc_md43',1,'int Hook_ConsoleCheckCanToggleNPC(CB::NPC::Type type)'],['../md_Articles_2Hooks.html#autotoc_md41',1,'int Hook_ConsoleSpawnNPC(CB::NPC::Type type)']]],
  ['cb_3a_3anpc_3a_3atype_20type_20bool_20isplural_9',['string Hook_ConsoleNPCTypeToName(CB::NPC::Type type, bool isPlural)',['../md_Articles_2Hooks.html#autotoc_md40',1,'']]],
  ['cb_3a_3aroom_10',['CB::Room',['../md_Articles_2Hooks.html#autotoc_md24',1,'bool Hook_FillRoom(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Room.html&quot; title=&quot;CB::Room&quot;&gt;CB::Room&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md25',1,'void Hook_PostFillRoom(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Room.html&quot; title=&quot;CB::Room&quot;&gt;CB::Room&lt;/a&gt;)']]],
  ['cb_3a_3aroomtemplate_20int_20rmeshversion_20b3d_3a_3astream_20string_20entityname_11',['bool Hook_LoadRoomTemplateEntity(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1RoomTemplate.html&quot; title=&quot;CB::RoomTemplate&quot;&gt;CB::RoomTemplate&lt;/a&gt;, int rMeshVersion, &lt;a class=&quot;el&quot; href=&quot;classB3D_1_1Stream.html&quot; title=&quot;B3D::Stream&quot;&gt;B3D::Stream&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; entityName)',['../md_Articles_2Hooks.html#autotoc_md26',1,'']]],
  ['cb_3a_3ascp914_3a_3asetting_20float_20x_20float_20y_20float_20z_12',['bool Hook_Use914(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;, CB::SCP914::Setting, float x, float y, float z)',['../md_Articles_2Hooks.html#autotoc_md48',1,'']]],
  ['cmd_13',['bool Hook_ExecuteConsoleCommand(&lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; cmd)',['../md_Articles_2Hooks.html#autotoc_md10',1,'']]]
];
